---
# tasks file for openstack-ansible-hardening
- name: Check cinder.conf  ownership and perms
  file:
    path:  /etc/cinder/cinder.conf
    owner: root
    group: cinder
    mode: 0640
  tags:
   - master

- name: Check api-paste.ini ownership and perms
  file:
    path:  /etc/cinder/api-paste-ini
    owner: root
    group: cinder
    mode: 0640
  tags:
   - master

- name: Check policy.json ownership and perms
  file:
    path:  /etc/cinder/policy.json
    owner: root
    group: cinder
    mode: 0640
  tags:
   - master

- name: Check rootwrap.conf ownership and perms
  file:
    path:  /etc/cinder/rootwrap.conf
    owner: root
    group: cinder
    mode: 0640
  tags:
   - master

- name: Is keystone used for authentication?
  lineinfile:
    dest:  /etc/cinder/cinder.conf
    regexp: '^(#)auth_strategy'
    line: 'auth_strategy=keystone'
    insertafter: EOF
  tags: master

- name: TODO Is secure protocol used for authentication? (auth_uri & insecure)
  lineinfile:
    dest:  /etc/cinder/cinder.conf
    regexp: ''
    line: ''
    insertafter: EOF
  tags: todo

- name: Does cinder communicate with glance over TLS?
  lineinfile:
    dest:  /etc/cinder/cinder.conf
    regexp: '^(#)glance_api_insecure'
    line: 'glance_api_insecure = False'
    insertafter: EOF
  tags:
   - master

- name: Is NAS operating in a secure environment (nas_secure_file_permissions)?
  lineinfile:
    dest:  /etc/cinder/cinder.conf
    regexp: '^(#)nas_secure_file_permissions'
    line: 'nas_secure_file_permissions = auto'
    insertafter: EOF
  tags:
   - master

   - name: Is NAS operating in a secure environment (nas_secure_file_operations)?
     lineinfile:
       dest:  /etc/cinder/cinder.conf
       regexp: '^(#)nas_secure_file_permissions'
       line: 'nas_secure_file_operations = auto'
       insertafter: EOF
     tags:
      - master
