---
# tasks file for openstack-ansible-hardening
- name: Check nova.conf ownership and perms
  file:
    path:  /etc/nova/nova.conf
    owner: root
    group: nova
    mode: 0640
  tags: master

- name: Check api-paste.ini ownership and perms
  file:
    path:  /etc/nova/api-paste-ini
    owner: root
    group: nova
    mode: 0640
  tags: master

- name: Check policy.json ownership and perms
  file:
    path:  /etc/nova/policy.json
    owner: root
    group: nova
    mode: 0640
  tags: master

- name: Check rootwrap.conf ownership and perms
  file:
    path:  /etc/nova/rootwrap.conf
    owner: root
    group: nova
    mode: 0640
  tags: master

- name: Is keystone used for authentication?
  lineinfile:
    dest:  /etc/nova/nova.conf
    regexp: '^(#)auth_strategy'
    line: 'auth_strategy=keystone'
    insertafter: EOF
  tags: master

- name: Is secure protocol used for authentication? (auth_uri & insecure)
  lineinfile:
    dest:  /etc/nova/nova.conf
    regexp: 'TODO'
    line: 'TODO'
    insertafter: EOF
  tags: master

- name: Does Nova communicate with Glance securely?
  lineinfile:
    dest:  /etc/nova/nova.conf
    regexp: '^(#)api_secure'
    line: 'api_secure=false'
    insertafter: EOF
  tags:
   - newton
   - mitaka

- name: Servers certificate is validated
  lineinfile:
    dest:  /etc/nova/nova.conf
    regexp: '^(#)verify_ssl'
    line: 'verify_ssl=true'
    insertafter: EOF
  tags:
   - master
   - ocata
   - newton

# Todo
# password_length
# hash_algorithms
# enable_certificate_validation
# memcache_security_strategy
# verify_glance_signatures
# default_trusted_certificate_ids
