---
# tasks file for openstack-ansible-hardening
- name: Check keystone.conf ownership and perms
  file:
    path: /etc/keystone/keystone.conf
    owner: keystone
    group: keystone
    mode: 0640
  tags: master

- name: Check keystone-paste.ini ownership and perms
  file:
    path: /etc/keystone/keystone-paste.ini
    owner: keystone
    group: keystone
    mode: 0640
  tags: master

- name: Check policy.json ownership and perms
  file:
    path: /etc/keystone/policy.json
    owner: keystone
    group: keystone
    mode: 0640
  tags: master

- name: Check logging.conf ownership and perms
  file:
    path: /etc/keystone/logging.conf
    owner: keystone
    group: keystone
    mode: 0640
  tags: master

- name: Check credential-keys 0 ownership and perms
  file:
    path: /etc/keystone/credential-keys/0
    owner: keystone
    group: keystone
    mode: 0640
  tags: master

- name: Check credential-keys 1 ownership and perms
  file:
    path: /etc/keystone/credential-keys/1
    owner: keystone
    group: keystone
    mode: 0640
  tags: master

- name: Check ferney-keys 0 ownership and perms
  file:
    path: /etc/keystone/fernet-keys/0
    owner: keystone
    group: keystone
    mode: 0640
  tags: master

- name: Check ferney-keys 1 ownership and perms
  file:
    path: /etc/keystone/fernet-keys/1
    owner: keystone
    group: keystone
    mode: 0640
  tags: master

- name: Check insecure_debug is false
  lineinfile:
    state: present
    dest: /etc/keystone/keystone.conf
    regexp: '^(#)?insecure_debug'
    line: 'insecure_debug = false'
  tags: master

- name: Check notification_format is cadf
  lineinfile:
    dest: /etc/keystone/keystone.conf
    regexp: '^notification_format.=.basic|^#ThisValueHere'
    line: 'notification_format = cadf'
    insertafter: EOF
  tags: master

- name: Is max_request_body_size set to default (114688)?
  lineinfile:
    dest: /etc/keystone/keystone.conf
    regexp: '^notification_format.=.basic|^#ThisValueHere'
    line: 'notification_format = cadf'
    insertafter: EOF
  tags: master

- name: Disable admin token in /etc/keystone/keystone.conf
  lineinfile:
    dest: /etc/keystone/keystone.conf
    regexp: '^notification_format.=.basic|^#ThisValueHere'
    line: 'notification_format = cadf'
    insertafter: EOF
  tags: master

