---
# tasks file for openstack-ansible-hardening
- name: Check glance-api-paste.ini ownership and perms
  file:
    path:  /etc/glance/glance-api-paste.ini
    owner: root
    group: glance
    mode: 0640
  tags: master

- name: Check api-paste.ini ownership and perms
  file:
    path:  /etc/nova/api-paste-ini
    owner: root
    group: nova
    mode: 0640
  tags: master

- name: Check policy.json ownership and perms
  file:
    path:  /etc/nova/policy.json
    owner: root
    group: nova
    mode: 0640
  tags: master

- name: Check rootwrap.conf ownership and perms
  file:
    path:  /etc/nova/rootwrap.conf
    owner: root
    group: nova
    mode: 0640
  tags: master

- name: Is keystone used for authentication?
  lineinfile:
    path:  /etc/nova/nova.conf
    owner: root
    group: nova
    mode: 0640
  tags: master

- name: Is keystone used for authentication?
  lineinfile:
    dest:  /etc/nova/nova.conf
    regexp: '^notification_format.=.basic|^#ThisValueHere'
    line: 'notification_format = cadf'
    insertafter: EOF
  tags: master

- name: Is secure protocol used for authentication?
  lineinfile:
    dest:  /etc/nova/nova.conf
    regexp: '^notification_format.=.basic|^#ThisValueHere'
    line: 'notification_format = cadf'
    insertafter: EOF
  tags: master

- name: Does Nova communicate with Glance securely?
  lineinfile:
    dest:  /etc/nova/nova.conf
    regexp: '^notification_format.=.basic|^#ThisValueHere'
    line: 'notification_format = cadf'
    insertafter: EOF
  tags: master
