---
# tasks file for openstack-ansible-hardening
- name: Check glance-api-paste.ini ownership and perms
  file:
    path:  /etc/glance/glance-api-paste.ini
    owner: root
    group: glance
    mode: 0640
  tags:
   - master

- name: Check glance-api.conf ownership and perms
  file:
    path:  /etc/glance/glance-api.conf
    owner: root
    group: glance
    mode: 0640
  tags:
   - master

- name: Check glance-manage.conf ownership and perms
  file:
    path:  /etc/glance/glance-manage.conf
    owner: root
    group: glance
    mode: 0640
  tags:
   - master

- name: Check glance-registry-paste.ini ownership and perms
  file:
    path:  /etc/glance/glance-registry-paste.ini
    owner: root
    group: glance
    mode: 0640
  tags:
   - master

- name: Check glance-registry.conf ownership and perms
  lineinfile:
    path:  /etc/glance/glance-registry.conf
    owner: root
    group: glance
    mode: 0640
  tags:
   - master

- name: Check glance-scrubber.conf ownership and perms
  lineinfile:
    path:  /etc/glance/glance-scrubber.conf
    owner: root
    group: glance
    mode: 0640
  tags:
   - master

- name: Check glance-swift-store.conf ownership and perms
  lineinfile:
    path:  /etc/glance/glance-swift-store.conf
    owner: root
    group: glance
    mode: 0640
  tags:
   - master

- name: Check policy.json ownership and perms
  lineinfile:
    path:  /etc/glance/policy.json
    owner: root
    group: glance
    mode: 0640
  tags:
   - master

  - name: Check schema-image.json ownership and perms
    lineinfile:
      path:  /etc/glance/schema-image.json
      owner: root
      group: glance
      mode: 0640
  tags:
   - master

  - name: Check schema.json ownership and perms
    lineinfile:
      path:  /etc/glance/schema.json
      owner: root
      group: glance
      mode: 0640
  tags:
   - master

- name: Is keystone used for authentication?
  lineinfile:
    dest:  /etc/glance/glance-api.conf
    regexp: '^(#)auth_strategy'
    line: 'auth_strategy=keystone'
    insertafter: EOF
  tags:
   - master

- name: TODO TLS enabled for authentication?
  lineinfile:
    dest:  /etc/glance/glance-api.conf
    regexp: '^(#)auth_uri'
    line: 'auth_uri'
    insertafter: EOF
  tags:
     - todo
