---
# tasks file for openstack-ansible-hardening
- name: Check neutron.conf  ownership and perms
  file:
    path:  /etc/neutron/neutron.conf
    owner: root
    group: neutron
    mode: 0640
  tags:
   - master

- name: Check api-paste.ini ownership and perms
  file:
    path:  /etc/nova/api-paste.ini
    owner: root
    group: neutron
    mode: 0640
  tags:
   - master

- name: Check policy.json ownership and perms
  file:
    path:  /etc/neutron/policy.json
    owner: root
    group: neutron
    mode: 0640
  tags:
   - master

- name: Check rootwrap.conf ownership and perms
  file:
    path:  /etc/neutron/rootwrap.conf
    owner: root
    group: neutron
    mode: 0640
  tags:
   - master

- name: Is keystone used for authentication?
  lineinfile:
    dest:  /etc/neutron/neutron.conf
    regexp: '^(#)auth_strategy'
    line: 'auth_strategy=keystone'
    insertafter: EOF
  tags:
   - master

- name: TODO Is secure protocol used for authentication? (auth_uri & insecure)
  lineinfile:
    dest:  /etc/nova/nova.conf
    regexp: ''
    line: ''
    insertafter: EOF
  tags: todo

- name: Does Nova communicate with Glance securely?
  lineinfile:
    dest:  /etc/nova/nova.conf
    regexp: '^notification_format.=.basic|^#ThisValueHere'
    line: 'notification_format = cadf'
    insertafter: EOF
  tags:
   - master
